# Generated by Django 4.0.5 on 2022-10-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_housewifedetails_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housewifedetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='retireddetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='country',
        ),
    ]
