# Generated by Django 4.0.3 on 2022-10-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0002_cibil_cibil_loan_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cibil',
            name='cibil_loan_type_id',
        ),
    ]
