# Generated by Django 2.2.7 on 2020-10-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200913_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='remark',
            field=models.CharField(max_length=900),
        ),
    ]
