# Generated by Django 2.2.7 on 2020-10-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201024_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_details',
            name='bank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit_details',
            name='card_age',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit_details',
            name='card_belong',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit_details',
            name='credit_limit',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit_details',
            name='limit_utilize',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit_details',
            name='moratorium',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='credit_details',
            name='payment_delay',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='bank',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='bounces',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='emi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='emi_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='emi_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='loan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='loan_belong',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='moratorium',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='product',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loan_details',
            name='roi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
