# Generated by Django 2.2.7 on 2020-11-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20201030_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan_details',
            name='loan_belong',
        ),
    ]
