# Generated by Django 2.2.7 on 2020-11-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_loan_details_loan_belong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit_details',
            name='card_belong',
        ),
    ]
