# Generated by Django 3.1.4 on 2021-01-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_credit_details_card_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='date',
            field=models.CharField(default='============ RESTART: C:/Users/abhisiddhi/OneDrive/Desktop/dates.py ============', max_length=100),
            preserve_default=False,
        ),
    ]
