# Generated by Django 2.2.7 on 2020-10-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_policy_master',
            name='months',
            field=models.BigIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod_policy_master',
            name='processing_fee',
            field=models.BigIntegerField(default=1500),
            preserve_default=False,
        ),
    ]
