# Generated by Django 2.2.7 on 2020-10-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_profee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profee',
            name='pro',
            field=models.BigIntegerField(),
        ),
    ]
