# Generated by Django 2.2.7 on 2020-10-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_auto_20201030_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='profee',
            name='rdate',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
