# Generated by Django 3.1.4 on 2021-01-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_cat',
            name='eff',
            field=models.CharField(default='2021-01-05 14:01:39.59', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bank_cat',
            name='ineff',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
