# Generated by Django 3.1.4 on 2021-01-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0010_auto_20210105_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_policy_master',
            name='eff_date',
            field=models.CharField(max_length=100),
        ),
    ]
