# Generated by Django 3.1.4 on 2021-01-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0012_auto_20210129_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pp_cibil',
            name='effec_date4',
        ),
        migrations.RemoveField(
            model_name='pp_cibil',
            name='ineffec_date4',
        ),
        migrations.RemoveField(
            model_name='pp_cocat_type',
            name='effec_date6',
        ),
        migrations.RemoveField(
            model_name='pp_cocat_type',
            name='ineffec_date6',
        ),
        migrations.RemoveField(
            model_name='pp_company_type',
            name='effec_date',
        ),
        migrations.RemoveField(
            model_name='pp_company_type',
            name='ineffec_date',
        ),
        migrations.RemoveField(
            model_name='pp_max_age',
            name='effec_date3',
        ),
        migrations.RemoveField(
            model_name='pp_max_age',
            name='ineffec_date3',
        ),
        migrations.RemoveField(
            model_name='pp_residence_type',
            name='effec_date2',
        ),
        migrations.RemoveField(
            model_name='pp_residence_type',
            name='ineffec_date2',
        ),
        migrations.RemoveField(
            model_name='pp_salary_type',
            name='effec_date1',
        ),
        migrations.RemoveField(
            model_name='pp_salary_type',
            name='ineffec_date1',
        ),
        migrations.RemoveField(
            model_name='pp_tenure',
            name='effec_date5',
        ),
        migrations.RemoveField(
            model_name='pp_tenure',
            name='ineffec_date5',
        ),
    ]
