# Generated by Django 3.1.4 on 2021-02-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_auto_20210129_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='pp_cocat_type',
            name='roi',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
