# Generated by Django 4.0.3 on 2022-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_companycat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenure', models.IntegerField()),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
